// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpsge-o2kNlvqrEZQG-Xi_qs8DSLCehFs',
    appId: '1:531801841122:web:f3bd537560e6e6c310edbb',
    messagingSenderId: '531801841122',
    projectId: 'up-todo-9c616',
    authDomain: 'up-todo-9c616.firebaseapp.com',
    storageBucket: 'up-todo-9c616.firebasestorage.app',
    measurementId: 'G-SWR95RM1KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVUEIy_y4sTxVwmPjLAx9E2MHgoWRN8Nk',
    appId: '1:531801841122:android:951cc8a2138d145f10edbb',
    messagingSenderId: '531801841122',
    projectId: 'up-todo-9c616',
    storageBucket: 'up-todo-9c616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGA0pJYTFZY97Rqcl6zjynmSStZ91A8wA',
    appId: '1:531801841122:ios:331dc08c3275f3b210edbb',
    messagingSenderId: '531801841122',
    projectId: 'up-todo-9c616',
    storageBucket: 'up-todo-9c616.firebasestorage.app',
    iosBundleId: 'com.mansursarkhanov.uptodo',
  );
}
